// Offline browser tests: no production data is written. Requires Playwright + Chromium.
const {chromium}=require('playwright');
const fs=require('fs');
const path=require('path');
const assert=require('node:assert/strict');
const ROOT=path.resolve(__dirname,'..');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.ERP_CHROME||undefined,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});let errors=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 await page.route('https://mumutori.test/**',route=>route.fulfill({contentType:'text/html',body:fs.readFileSync(path.join(ROOT,'index.html'),'utf8')}));
 await page.goto('https://mumutori.test/');
 let f=page.frameLocator('iframe');await f.locator('h1').waitFor();
 const stored=()=>page.frames()[1].evaluate(()=>JSON.parse(localStorage.getItem('mumutori-private-finance-v3')));
 const nav=async v=>{await f.locator('.nav-item[data-view="'+v+'"]').click();};
 const save=async()=>{await f.locator('#submit-record').click();await f.locator('[role="dialog"]').waitFor({state:'hidden',timeout:2500}).catch(async e=>{throw Error('Save failed: '+await f.locator('#form-error').textContent());});};
 await page.screenshot({path:'/tmp/mumutori-erp-overview.png'});
 await nav('products');await f.locator('[data-action="edit"][data-type="product"][data-id]').first().click();
 assert.equal(await f.locator('[role="dialog"] h2').textContent(),'상품 수정');
 const id=await f.locator('#f-id').inputValue();const oldName=await f.locator('#f-name').inputValue();
 await f.locator('#f-name').fill('검증 상품명');await f.locator('#f-price').fill('9900');
 await page.screenshot({path:'/tmp/mumutori-erp-product-modal.png'});await save();
 assert.equal((await stored()).products.find(p=>p.id===id).name,'검증 상품명');
 await page.reload();f=page.frameLocator('iframe');await f.locator('h1').waitFor();await nav('products');
 await f.locator('[data-action="edit"][data-id="'+id+'"]').click();assert.equal(await f.locator('#f-name').inputValue(),'검증 상품명');
 await f.locator('#f-name').fill('저장하지 않을 내용');await f.locator('[aria-label="닫기"]').click();assert.equal((await stored()).products.find(p=>p.id===id).name,'검증 상품명');
 console.log('PASS product modal, save, reload, discard');
 await nav('bank');await f.locator('[data-action="edit"][data-type="bank"]:not([data-id])').click();
 await f.locator('#f-direction').selectOption('입금');await f.locator('#f-description').fill('김현수 검증 충전');await f.locator('#f-amount').fill('123456');
 await f.locator('#f-category').selectOption('자금 충전');
 assert(!(await f.locator('#f-category').textContent()).includes('매출'));await save();
 const owner=(await stored()).bankTransactions.find(b=>b.description==='김현수 검증 충전');assert.equal(owner.category,'자금 충전');
 console.log('PASS owner deposits cannot be revenue');
 await nav('stock');await f.locator('[data-action="count"][data-id="'+id+'"]').click();await f.locator('#f-qty').fill('5');await save();
 await f.locator('[data-action="move-product"][data-id="'+id+'"]').click();await f.locator('#f-type').selectOption('출고');await f.locator('#f-qty').fill('6');await f.locator('#submit-record').click();
 assert.match(await f.locator('#form-error').textContent(),/음수/);await f.locator('#f-qty').fill('2');await save();
 assert.equal((await stored()).erp.movements.filter(m=>m.sku===id).length,2);
 console.log('PASS stock count, negative prevention, outbound');
 await nav('purchases');await f.locator('[data-action="edit"][data-type="purchase"]:not([data-id])').click();
 await f.locator('#f-orderNo').fill('ERP-TEST-P1');await f.locator('#f-vendor').fill('검증 구매처');
 await f.locator('#f-purchase').fill('10000');await f.locator('#f-shipping').fill('2000');await f.locator('#f-customs').fill('0');
 await f.locator('[data-line="0"][data-key="sku"]').selectOption(id);await f.locator('[data-line="0"][data-key="qty"]').fill('4');await save();
 await f.locator('[data-action="receive"][data-id="ERP-TEST-P1"]').click();assert.equal(await f.locator('#f-qty').inputValue(),'4');await save();
 console.log('PASS purchase registration and linked receipt');
 await nav('bank');await f.locator('[data-action="edit"][data-type="bank"]:not([data-id])').click();await f.locator('#f-direction').selectOption('입금');
 await f.locator('#f-description').fill('검증 판매 수금');await f.locator('#f-amount').fill('20000');await f.locator('#f-category').selectOption('매출 수금');await save();
 const receipt=(await stored()).bankTransactions.find(b=>b.description==='검증 판매 수금');
 await nav('sales');await f.locator('[data-action="edit"][data-type="sale"]:not([data-id])').click();
 await f.locator('#f-orderId').fill('ERP-TEST-S1');await f.locator('#f-sku').selectOption(id);await f.locator('#f-quantity').fill('2');await f.locator('#f-salesGross').fill('20000');
 await f.locator('[data-action="calc-settlement"]').click();await f.locator('input[name="linkedBankIds"][value="'+receipt.id+'"]').check();await save();
 const sold=(await stored()).finance.channelTransactions.find(s=>s.orderId==='ERP-TEST-S1');assert.equal(sold.settlementBase,20000);assert.deepEqual(sold.linkedBankIds,[receipt.id]);
 await f.locator('[data-action="ship"][data-id="'+sold.id+'"]').click();await save();
 console.log('PASS sales, cash linkage, linked shipment');
 await nav('settings');const backup=await stored();backup.products.find(p=>p.id===id).name='가져온 이름';
 await f.locator('#backup-file').setInputFiles({name:'test.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});
 await f.locator('#f-preference').selectOption('incoming');await save();assert.equal((await stored()).products.find(p=>p.id===id).name,'가져온 이름');
 console.log('PASS explicit backup merge');
 await nav('products');await f.locator('[data-action="edit"][data-id="'+id+'"]').click();await f.locator('#f-name').fill('저장 실패 테스트');
 await page.evaluate(()=>{Storage.prototype.setItem=function(){throw new DOMException('Full','QuotaExceededError')};});await f.locator('#submit-record').click();
 // Storage.prototype is realm-specific; inject into the actual iframe.
 if(!await f.locator('[role="dialog"]').count()){
   await f.locator('[data-action="edit"][data-id="'+id+'"]').click();await f.locator('#f-name').fill('실패 후 초안');
 }
 await page.frames()[1].evaluate(()=>{Storage.prototype.setItem=function(){throw new DOMException('Full','QuotaExceededError')};});
 await f.locator('#submit-record').click();assert.match(await f.locator('#form-error').textContent(),/저장하지 못했습니다/);
 console.log('PASS storage failure keeps draft');
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/tmp/mumutori-erp-mobile.png'});
 const bounds=await f.locator('.modal').boundingBox();assert(bounds.x>=0&&bounds.x+bounds.width<=391);
 assert.equal(errors.length,0,JSON.stringify(errors));
 console.log('PASS mobile dialog and no runtime errors');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
