export default function finance(ctx){
  const {C,data,state,esc,won,money,badge,head,metric,link,btn,filters}=ctx;
  const s=C.financeSummary(data,state.month);
  const purchases=C.active(C.purchases(data)).filter(p=>!state.month||(p.date||p.receivedAt||'').startsWith(state.month));
  const sales=C.active(data.finance.channelTransactions).filter(r=>!state.month||r.date?.startsWith(state.month));
  const complete=purchases.filter(p=>C.purchaseCost(p).complete),unknown=purchases.length-complete.length;
  const invoiced=sales.filter(r=>r.supplyAmount!=null&&r.vatAmount!=null&&r.invoiceNumber);
  const channels=[...new Set(sales.map(r=>r.channel||'미지정'))].map(name=>({name,amount:C.sum(sales.filter(r=>(r.channel||'미지정')===name),'salesGross')})).sort((a,b)=>b.amount-a.amount);
  const max=Math.max(1,...channels.map(r=>Math.abs(r.amount)));
  return head('숫자로 보는 무무토리','판매·구매·자금팀의 원장을 모아, 확인할 숫자와 증빙을 점검합니다.',link('sales','매출 원장 보기'))+
    `<div class="toolbar"><div class="filters"><label>조회 월 <input type="month" id="month" aria-label="조회 월" data-filter="month" value="${esc(state.month)}"></label>${state.month?btn('전체 기간','clear-month',{},'text'):badge('전체 기록 기준')}</div></div>`+
    `<div class="metrics">${metric('기록된 매출',s.salesGross,'원','부가세 포함 · '+s.salesCount+'건')}${metric('매출 정산 예정액',s.expected,'원','판매 수수료 반영 · 실제 수금과 별도')}${metric('확인된 매입 결제액',C.sum(purchases,p=>C.purchaseCost(p).known),'원','미확인 항목 제외 · '+unknown+'건 원가 확인 필요')}${metric('연결 건의 남은 수금',s.receivable,'원','미연결 '+s.unlinked+'건은 별도 확인')}</div>`+
    `<div class="grid2"><section class="panel"><div class="panelhead"><h2>채널별 매출</h2><span class="section-en">SALES MIX</span></div><div class="panelbody">${channels.length?channels.map(c=>`<div class="channel-row"><div><b>${esc(c.name)}</b><strong class="${c.amount<0?'minus':'plus'}">${money(c.amount)}</strong></div><div class="bar-track"><span style="width:${Math.abs(c.amount)/max*100}%"></span></div></div>`).join(''):'<div class="empty">매출을 등록하면 채널별로 모아 보여드려요.</div>'}${link('sales','판매팀 원장으로 이동')}</div></section><section class="panel"><div class="panelhead"><h2>마감 전 확인</h2>${badge('확인 필요','amber')}</div><div class="panelbody"><a class="check-row" href="sales.html?attention=unlinked"><span><b>수금 미연결</b><small>실제 입금과 매출 문서 연결</small></span><strong>${s.unlinked}<em>건 ↗</em></strong></a><a class="check-row" href="purchases.html?attention=cost"><span><b>매입 원가 미확정</b><small>구매·배송·통관 금액 확인</small></span><strong>${unknown}<em>건 ↗</em></strong></a><a class="check-row" href="bank.html?attention=pending"><span><b>자금 분류 확인</b><small>통장 입출금의 용도 확인</small></span><strong>${s.pending}<em>건 ↗</em></strong></a></div></section></div>`+
    `<div class="grid2"><section class="panel"><div class="panelhead"><h2>세금계산서 기록</h2>${badge('입력된 증빙 기준')}</div><div class="panelbody"><div class="mini-row"><span>공급가액</span><strong>${money(C.sum(invoiced,'supplyAmount'))}</strong></div><div class="mini-row"><span>부가세</span><strong class="accent-orange">${money(C.sum(invoiced,'vatAmount'))}</strong></div><p>승인번호·공급가액·부가세가 모두 입력된 ${invoiced.length}건 기준입니다. 실제 발행·신고 결과는 증빙과 확인하세요.</p>${link('sales','매출 증빙 입력하기')}</div></section><section class="panel"><div class="panelhead"><h2>원가 확인 범위</h2>${badge('구매팀 연결')}</div><div class="panelbody"><div class="mini-row"><span>금액이 모두 확인된 매입</span><strong>${complete.length}건</strong></div><div class="mini-row"><span>위 매입의 공제 부가세 제외 원가</span><strong>${money(C.sum(complete,p=>C.purchaseCost(p).net))}</strong></div><p>매입 원가는 판매된 상품의 원가와 다릅니다. 재고와 판매 원가가 연결되기 전에는 순이익으로 계산하지 않습니다.</p>${link('purchases','매입·원가 확인하기')}</div></section></div>`;
}
