export default function overview(ctx){
  const {C,data,state,esc,won,money,dateTime,badge,btn,icon,metric,link,departmentCards,workflowStrip}=ctx;
  const s=C.financeSummary(data),products=data.products.filter(p=>p.active!==false);
  const counts=products.filter(p=>!C.stock(data,p.id,state.warehouse).known).length;
  const inbound=C.active(C.purchases(data)).filter(p=>C.sum(p.lines,'qty')>C.sum(p.lines,l=>C.moved(data,'purchase',p.orderNo,l.sku))).length;
  const date=new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',month:'long',day:'numeric',weekday:'long'}).format(new Date());
  const tasks=[['bank','pending','자금팀','분류를 기다리는 거래',s.pending,'건','blue'],['sales','unlinked','판매팀','수금 연결이 필요한 매출',s.unlinked,'건','pink'],['stock','uncounted','물류팀','첫 실사가 필요한 상품',counts,'개','green'],['purchases','unreceived','구매팀','입고 기록을 확인할 매입',inbound,'건','purple']];
  return `<div class="home-heading"><div><div class="eyebrow">MUMUTORI WORKSPACE <span class="live-pill">● OPEN FOR WORK</span></div><h1>오늘도, 무무토리<span class="title-dot">.</span></h1></div><span class="today-date">${date}</span></div>`+
    `<section class="studio-hero"><div class="hero-copy"><span class="hero-kicker">SMALL THINGS. BIG POSSIBILITIES.</span><h2>작은 기록이 모여,<br><span>우리의 다음</span>이 되니까.</h2><p>상품부터 정산까지, 각자의 일은 선명하게.<br>모든 흐름은 하나로 이어지는 무무토리 스튜디오.</p><div class="hero-actions">${btn('오늘의 기록 남기기 ↗','quick',{},'hero-cta')}<a href="products.html">상품팀으로 이동 <span>→</span></a></div></div><div class="hero-art" aria-hidden="true"><div class="art-grid"></div><div class="orbit-line"></div><div class="art-sticker sticker-top">EVERY LITTLE<br>THING COUNTS ↗</div><div class="mascot"><i class="mascot-eye eye-left"></i><i class="mascot-eye eye-right"></i><i class="mascot-smile"></i><span class="mascot-label">m.</span></div><div class="flower-orbit"><span>✳</span></div><span class="art-star">✦</span><div class="art-sticker sticker-bottom">GOOD THINGS<br><b>IN THE MAKING.</b></div></div><span class="hero-edition">MUMUTORI STUDIO / VOL. 01</span></section>`+
    `<div class="section-title"><h2>한눈에 보는 현재</h2><span>전체 기록 기준 · 실제 원장 범위</span>${link('finance','재무팀에서 자세히')}</div><div class="metrics home-metrics">${metric('기록된 매출',s.salesGross,'원','부가세 포함 · '+s.salesCount+'건')}${metric('외부 입금',s.inflow,'원','자금 충전·회수 포함 / 매출과 별도')}${metric('외부 출금',s.outflow,'원','매입·비용 등 / 내부 이체 제외')}${metric('함께 관리하는 상품',products.length,'개','운영 중인 상품 · 중단 이력 별도 보관')}</div>`+
    `<div class="section-title"><h2>우리의 작은 부서들<span class="count-pill">06</span></h2><span>각자의 업무에서 시작해 보세요.</span></div>${departmentCards()}`+
    `<div class="home-bottom"><section class="panel task-panel"><div class="panelhead"><h2>다음으로 챙길 일 <span class="accent-orange">✳</span></h2>${badge('원장 점검')}</div><div class="task-list">${tasks.map(([v,a,dept,label,count,unit,tone])=>`<a class="task-link" href="${v}.html?attention=${a}"><span class="task-dept tone-${tone}">${dept}</span><b>${label}</b><strong>${won(count)}<em>${unit}</em></strong><span class="task-arrow">↗</span></a>`).join('')}</div><div class="task-foot">과거 기록을 포함한 확인 목록입니다. 실제 미수금·미입고 확정 건수는 아닙니다.</div></section><section class="panel activity-panel"><div class="panelhead"><h2>최근의 발자취</h2>${link('audit','전체 보기')}</div><div class="panelbody">${data.erp.audit.slice(0,3).map(a=>`<div class="activity"><i></i><div><b>${esc(a.label)}</b><small>${esc(a.action)} · ${dateTime(a.date)}</small></div></div>`).join('')||'<div class="activity-empty"><span>↗</span><b>첫 기록을 기다리고 있어요.</b><p>등록과 수정의 발자취가<br>이곳에 차곡차곡 쌓입니다.</p></div>'}</div></section></div>${workflowStrip()}`;
}
