export default function renderPage(ctx){
  const {C,data,state,esc,won,money,dateTime,badge,btn,options,TYPE_LABEL,accountName,findProduct,matches,inMonth,visible,byDate,rowClass,rowsTable,editButtons,filters,metric,head,accountSummary,link,icon,departmentCards,workflowStrip}=ctx;
    const rows=data.products.filter(p=>matches(p,['id','name','memo','barcode','supplier'])&&(state.filter==='전체'?p.active!==false:p.salesStatus===state.filter)).sort((a,b)=>a.id.localeCompare(b.id));
    return head('상품 관리','상품 정보와 판매 상태를 수정 창에서 관리합니다.',btn('+ 상품 등록','edit',{type:'product'},'primary'))+
      `<div class="metrics">${metric('관리 상품',data.products.length,'개','공통 상품번호로 부서 간 연결')}${metric('판매 중',data.products.filter(p=>p.salesStatus==='판매 중').length,'개','현재 판매 상태 기준')}${metric('판매 준비',data.products.filter(p=>p.salesStatus==='판매 준비').length,'개','상품 정보와 판매가 준비')}${metric('정보 확인 필요',data.products.filter(p=>p.salesStatus==='확인 필요').length,'개','상품팀 확인 대기')}</div>`+
      filters('상품명, 관리번호, 바코드 검색',C.STATUS,false,false)+
      `<div class="note" style="margin-bottom:18px">기본 목록은 운영 중인 상품입니다. 판매 중단 상품은 상태 필터에서 조회할 수 있습니다. 상품의 관리번호는 매입·매출·재고 연결에 사용됩니다.</div>`+
      rowsTable(['상품','상태','구분','#기본 판매가','구매처','관리'],rows,p=>`<tr><td><div class="product-cell">${p.imageData&&/^data:image\/(png|jpeg|webp);base64,/.test(p.imageData)?`<img class="thumb" src="${esc(p.imageData)}" alt="" loading="lazy">`:'<span class="thumb blank">◇</span>'}<div><strong>${esc(p.name)}</strong><span class="sub">${esc(p.id)}${p.barcode?' · '+esc(p.barcode):''}</span></div></div></td><td>${badge(p.salesStatus,p.salesStatus==='판매 중'?'green':p.salesStatus==='확인 필요'?'amber':'')}</td><td>${esc(p.type||'판매상품')}</td><td class="num">${p.price!=null&&p.price!==''?money(p.price):'미설정'}</td><td>${esc(p.supplier||'—')}</td><td>${editButtons('product',p)}<div class="rowaction">${link('purchases','매입',p.id,'table-link')}${link('stock','재고',p.id,'table-link')}${link('sales','매출',p.id,'table-link')}</div></td></tr>`);
  }
