export default function renderPage(ctx){
  const {C,data,state,esc,won,money,dateTime,badge,btn,options,TYPE_LABEL,accountName,findProduct,matches,inMonth,visible,byDate,rowClass,rowsTable,editButtons,filters,metric,head,accountSummary,link,icon,departmentCards,workflowStrip}=ctx;
    const rows=byDate(visible(data.finance.channelTransactions).filter(r=>matches(r,['id','sku','orderId','productName','customer','channel'])&&inMonth(r)&&(!state.attention||state.attention!=='unlinked'||!(r.linkedBankIds||[]).length)&&(state.filter==='전체'||r.channel===state.filter)));
    const s=C.financeSummary(data,state.month);
    return head('매출·정산','판매 기록과 실제 수금을 연결하고 출고를 관리하세요.',btn('+ 매출 등록','edit',{type:'sale'},'primary'))+
      `<div class="metrics">${metric('기록된 매출',s.salesGross,'원','부가세 포함 · 보유 자료 범위')}${metric('정산 예정액',s.expected,'원','기록된 수수료 반영')}${metric('수금 미연결',s.unlinked,'건','통장 거래 연결 필요')}${metric('연결 건의 남은 수금',s.receivable,'원','수금 연결한 기록만 집계')}</div>`+
      filters('주문번호, 상품명, 거래처 검색',[...new Set(data.finance.channelTransactions.map(r=>r.channel).filter(Boolean))],true)+
      rowsTable(['매출일','주문·품목','채널 / 거래처','#수량','#매출액','#정산액','수금 / 출고','관리'],rows,r=>{const t=C.saleTotals(data,r),shipped=r.sku?C.moved(data,'sale',r.id,r.sku):0;return `<tr ${rowClass(r)}><td class="date">${esc(r.date)}</td><td class="maincell"><b>${esc(r.productName)}</b><span class="sub">${esc(r.orderId)}${r.sku?' · '+esc(r.sku):''}</span></td><td>${esc(r.channel)}<span class="sub">${esc(r.customer||'')}</span></td><td class="num">${won(r.quantity)}</td><td class="num">${money(r.salesGross)}</td><td class="num">${money(t.expected)}</td><td>${badge(t.status,t.status==='수금 완료'?'green':'amber')}<span class="sub">${r.sku?`출고 ${shipped} / ${r.quantity}`:'재고 상품 미연결'}</span>${r.sku?link('stock','상품 재고',r.sku,'table-link'):''}${(r.linkedBankIds||[]).map(id=>link('bank','연결 입금',id,'table-link')).join('')}</td><td>${editButtons('sale',r,r.sku&&r.quantity>shipped?btn('출고','ship',{id:r.id},'text'):'')}</td></tr>`;});
  }
